rank(Michael_Phelps, 1).
rank(Larisa_Latynina, 2).
rank(Marit_Bjorgen, 3).
rank(Nikolai_Andrianov, 4).
rank(Ole_Einar_Bjorndalen, 5).
rank(Boris_Shakhlin, 6).
rank(Edoardo_Mangiarotti, 7).
rank(Takashi_Ono, 8).
rank(Paavo_Nurmi, 9).
rank(Birgit_Fischer, 10).
rank(Bjorn_Daehlie, 11).
rank(Sawao_Kato, 12).
rank(Jenny_Thompson, 13).
rank(Ryan_Lochte, 14).
rank(Dara_Torres, 15).
rank(Alexei_Nemov, 16).
rank(Natalie_Coughlin, 17).
rank(Mark_Spitz, 18).
rank(Matt_Biondi, 19).
rank(Vera_Caslavska, 20).
nation(Michael_Phelps, United_States).
nation(Larisa_Latynina, Soviet_Union).
nation(Marit_Bjorgen, Norway).
nation(Nikolai_Andrianov, Soviet_Union).
nation(Ole_Einar_Bjorndalen, Norway).
nation(Boris_Shakhlin, Soviet_Union).
nation(Edoardo_Mangiarotti, Italy).
nation(Takashi_Ono, Japan).
nation(Paavo_Nurmi, Finland).
nation(Birgit_Fischer, Germany).
nation(Bjorn_Daehlie, Norway).
nation(Sawao_Kato, Japan).
nation(Jenny_Thompson, United_States).
nation(Ryan_Lochte, United_States).
nation(Dara_Torres, United_States).
nation(Alexei_Nemov, Russia).
nation(Natalie_Coughlin, United_States).
nation(Mark_Spitz, United_States).
nation(Matt_Biondi, United_States).
nation(Vera_Caslavska, Czechoslovakia).
sport(Michael_Phelps, Swimming).
sport(Larisa_Latynina, Gymnastics).
sport(Marit_Bjorgen, Cross_country_skiing).
sport(Nikolai_Andrianov, Gymnastics).
sport(Ole_Einar_Bjorndalen, Biathlon).
sport(Boris_Shakhlin, Gymnastics).
sport(Edoardo_Mangiarotti, Fencing).
sport(Takashi_Ono, Gymnastics).
sport(Paavo_Nurmi, Athletics).
sport(Birgit_Fischer, Canoeing).
sport(Bjorn_Daehlie, Cross_country_skiing).
sport(Sawao_Kato, Gymnastics).
sport(Jenny_Thompson, Swimming).
sport(Ryan_Lochte, Swimming).
sport(Dara_Torres, Swimming).
sport(Alexei_Nemov, Gymnastics).
sport(Natalie_Coughlin, Swimming).
sport(Mark_Spitz, Swimming).
sport(Matt_Biondi, Swimming).
sport(Vera_Caslavska, Gymnastics).
start_year(Michael_Phelps, 2004).
start_year(Larisa_Latynina, 1956).
start_year(Marit_Bjorgen, 2002).
start_year(Nikolai_Andrianov, 1972).
start_year(Ole_Einar_Bjorndalen, 1998).
start_year(Boris_Shakhlin, 1956).
start_year(Edoardo_Mangiarotti, 1936).
start_year(Takashi_Ono, 1952).
start_year(Paavo_Nurmi, 1920).
start_year(Birgit_Fischer, 1980).
start_year(Bjorn_Daehlie, 1992).
start_year(Sawao_Kato, 1968).
start_year(Jenny_Thompson, 1992).
start_year(Ryan_Lochte, 2004).
start_year(Dara_Torres, 1984).
start_year(Alexei_Nemov, 1996).
start_year(Natalie_Coughlin, 2004).
start_year(Mark_Spitz, 1968).
start_year(Matt_Biondi, 1984).
start_year(Vera_Caslavska, 1960).
end_year(Michael_Phelps, 2016).
end_year(Larisa_Latynina, 1964).
end_year(Marit_Bjorgen, 2018).
end_year(Nikolai_Andrianov, 1980).
end_year(Ole_Einar_Bjorndalen, 2014).
end_year(Boris_Shakhlin, 1964).
end_year(Edoardo_Mangiarotti, 1960).
end_year(Takashi_Ono, 1964).
end_year(Paavo_Nurmi, 1928).
end_year(Birgit_Fischer, 2004).
end_year(Bjorn_Daehlie, 1998).
end_year(Sawao_Kato, 1976).
end_year(Jenny_Thompson, 2004).
end_year(Ryan_Lochte, 2016).
end_year(Dara_Torres, 2008).
end_year(Alexei_Nemov, 2000).
end_year(Natalie_Coughlin, 2012).
end_year(Mark_Spitz, 1972).
end_year(Matt_Biondi, 1992).
end_year(Vera_Caslavska, 1968).
season(Michael_Phelps, Summer).
season(Larisa_Latynina, Summer).
season(Marit_Bjorgen, Winter).
season(Nikolai_Andrianov, Summer).
season(Ole_Einar_Bjorndalen, Winter).
season(Boris_Shakhlin, Summer).
season(Edoardo_Mangiarotti, Summer).
season(Takashi_Ono, Summer).
season(Paavo_Nurmi, Summer).
season(Birgit_Fischer, Summer).
season(Bjorn_Daehlie, Winter).
season(Sawao_Kato, Summer).
season(Jenny_Thompson, Summer).
season(Ryan_Lochte, Summer).
season(Dara_Torres, Summer).
season(Alexei_Nemov, Summer).
season(Natalie_Coughlin, Summer).
season(Mark_Spitz, Summer).
season(Matt_Biondi, Summer).
season(Vera_Caslavska, Summer).
gender(Michael_Phelps, M).
gender(Larisa_Latynina, F).
gender(Marit_Bjorgen, F).
gender(Nikolai_Andrianov, M).
gender(Ole_Einar_Bjorndalen, M).
gender(Boris_Shakhlin, M).
gender(Edoardo_Mangiarotti, M).
gender(Takashi_Ono, M).
gender(Paavo_Nurmi, M).
gender(Birgit_Fischer, F).
gender(Bjorn_Daehlie, M).
gender(Sawao_Kato, M).
gender(Jenny_Thompson, F).
gender(Ryan_Lochte, M).
gender(Dara_Torres, F).
gender(Alexei_Nemov, M).
gender(Natalie_Coughlin, F).
gender(Mark_Spitz, M).
gender(Matt_Biondi, M).
gender(Vera_Caslavska, F).
gold_no(Michael_Phelps, 23).
gold_no(Larisa_Latynina, 9).
gold_no(Marit_Bjorgen, 8).
gold_no(Nikolai_Andrianov, 7).
gold_no(Ole_Einar_Bjorndalen, 8).
gold_no(Boris_Shakhlin, 7).
gold_no(Edoardo_Mangiarotti, 6).
gold_no(Takashi_Ono, 5).
gold_no(Paavo_Nurmi, 9).
gold_no(Birgit_Fischer, 8).
gold_no(Bjorn_Daehlie, 8).
gold_no(Sawao_Kato, 8).
gold_no(Jenny_Thompson, 8).
gold_no(Ryan_Lochte, 6).
gold_no(Dara_Torres, 4).
gold_no(Alexei_Nemov, 4).
gold_no(Natalie_Coughlin, 3).
gold_no(Mark_Spitz, 9).
gold_no(Matt_Biondi, 8).
gold_no(Vera_Caslavska, 7).
silver_no(Michael_Phelps, 3).
silver_no(Larisa_Latynina, 5).
silver_no(Marit_Bjorgen, 4).
silver_no(Nikolai_Andrianov, 5).
silver_no(Ole_Einar_Bjorndalen, 4).
silver_no(Boris_Shakhlin, 4).
silver_no(Edoardo_Mangiarotti, 5).
silver_no(Takashi_Ono, 4).
silver_no(Paavo_Nurmi, 3).
silver_no(Birgit_Fischer, 4).
silver_no(Bjorn_Daehlie, 4).
silver_no(Sawao_Kato, 3).
silver_no(Jenny_Thompson, 3).
silver_no(Ryan_Lochte, 3).
silver_no(Dara_Torres, 4).
silver_no(Alexei_Nemov, 2).
silver_no(Natalie_Coughlin, 4).
silver_no(Mark_Spitz, 1).
silver_no(Matt_Biondi, 2).
silver_no(Vera_Caslavska, 4).
bronze_no(Michael_Phelps, 2).
bronze_no(Larisa_Latynina, 4).
bronze_no(Marit_Bjorgen, 3).
bronze_no(Nikolai_Andrianov, 3).
bronze_no(Ole_Einar_Bjorndalen, 1).
bronze_no(Boris_Shakhlin, 2).
bronze_no(Edoardo_Mangiarotti, 2).
bronze_no(Takashi_Ono, 4).
bronze_no(Paavo_Nurmi, 0).
bronze_no(Birgit_Fischer, 0).
bronze_no(Bjorn_Daehlie, 0).
bronze_no(Sawao_Kato, 1).
bronze_no(Jenny_Thompson, 1).
bronze_no(Ryan_Lochte, 3).
bronze_no(Dara_Torres, 4).
bronze_no(Alexei_Nemov, 6).
bronze_no(Natalie_Coughlin, 5).
bronze_no(Mark_Spitz, 1).
bronze_no(Matt_Biondi, 1).
bronze_no(Vera_Caslavska, 0).
total_no(Michael_Phelps, 28).
total_no(Larisa_Latynina, 18).
total_no(Marit_Bjorgen, 15).
total_no(Nikolai_Andrianov, 15).
total_no(Ole_Einar_Bjorndalen, 13).
total_no(Boris_Shakhlin, 13).
total_no(Edoardo_Mangiarotti, 13).
total_no(Takashi_Ono, 13).
total_no(Paavo_Nurmi, 12).
total_no(Birgit_Fischer, 12).
total_no(Bjorn_Daehlie, 12).
total_no(Sawao_Kato, 12).
total_no(Jenny_Thompson, 12).
total_no(Ryan_Lochte, 12).
total_no(Dara_Torres, 12).
total_no(Alexei_Nemov, 12).
total_no(Natalie_Coughlin, 12).
total_no(Mark_Spitz, 11).
total_no(Matt_Biondi, 11).
total_no(Vera_Caslavska, 11).


